### PR TITLE
Fix: install Metrics Configs for DBs

### PR DESCRIPTION
**Pull request by Emon46**
Signed-off-by: Emon46 <emon@appscode.com>

### CODE REVIEW

**Review by raihankhan — APPROVED** [review]
LGTM!

**Review by spectro30 — APPROVED** [review]
LGTM

**Comment by spectro30** [comment]
@TasdidurRahman , Please make the changes on ProxySQL branch.

**Review by pkbhowmick — APPROVED** [review]
LGTM!

**Review by Shaad7 — APPROVED** [review]
LGTM!

**Pull request merged**
